name: Make Pipeline

on:
  schedule:
    - cron: "0 * * * *"  # toutes les heures (UTC)
  workflow_dispatch:     # exécution manuelle via GitHub

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up GCP credentials
      env:
        GCP_CREDS: ${{ secrets.GCP_JSON }}
      run: |
        echo "$GCP_CREDS" > gcp_key.json

    - name: Run pipeline
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp_key.json
      run: python make_pipeline.py
